### ISSUE TITLE
大哥好，关于引用的问题

### ISSUE THREAD

**Issue by passlon** [NWPUMetaphysicsOffice/Yet-Another-LaTeX-Template-for-NPU-Thesis#107]
之前别的模版中\cite的序号是与正文一致，\upcite是在右上角，现在\cite是在右上角，请问现在如果想要与正文一致应该用什么指令，比如我在写综述的时候会用到“文献[1]研究了XXX”此时不需要放在上标

**Comment by polossk** [comment]
按照要求，您说的这种情况也是需要右上角标注引用的，这个问题我这周末增加一个命令好了，抱歉打工人时间并不是很充裕，您请见谅。

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年11月09日 20:45 |
| 收件人 | NWPUMetaphysicsOffice/Yet-Another-LaTeX-Template-for-NPU-Thesis ***@***.***> |
| 抄送人 | Subscribed ***@***.***> |
| 主题 | [NWPUMetaphysicsOffice/Yet-Another-LaTeX-Template-for-NPU-Thesis] 大哥好，关于引用的问题 (Issue #107) |

之前别的模版中\cite的序号是与正文一致，\upcite是在右上角，现在\cite是在右上角，请问现在如果想要与正文一致应该用什么指令，比如我在写综述的时候会用到“文献[1]研究了XXX”此时不需要放在上标

**Comment by passlon** [comment]
> 按照要求，您说的这种情况也是需要右上角标注引用的，这个问题我这周末增加一个命令好了，抱歉打工人时间并不是很充裕，您请见谅。
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 发送日期 | 2023年11月09日 20:45 | | 收件人 | NWPUMetaphysicsOffice/Yet-Another-LaTeX-Template-for-NPU-Thesis ***@***.***> | | 抄送人 | Subscribed ***@***.***> | | 主题 | [NWPUMetaphysicsOffice/Yet-Another-LaTeX-Template-for-NPU-Thesis] 大哥好，关于引用的问题 (Issue #107) | 之前别的模版中\cite的序号是与正文一致，\upcite是在右上角，现在\cite是在右上角，请问现在如果想要与正文一致应该用什么指令，比如我在写综述的时候会用到“文献[1]研究了XXX”此时不需要放在上标 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

谢谢大佬，我去看了格式文件，在cls文件第234行“\let\oldcite\cite ”，将原来的\cite命令保存为自定义的\oldcite，就是原来的\cite的功能，有空的话可以在文献引用的说说明里提一下，谢谢大佬。

**Comment by polossk** [comment]
您客气了，我再改一下

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年11月09日 21:06 |
| 收件人 | NWPUMetaphysicsOffice/Yet-Another-LaTeX-Template-for-NPU-Thesis ***@***.***> |
| 抄送人 | Shangkun ***@***.***>,
Comment ***@***.***> |
| 主题 | Re: [NWPUMetaphysicsOffice/Yet-Another-LaTeX-Template-for-NPU-Thesis] 大哥好，关于引用的问题 (Issue #107) |

按照要求，您说的这种情况也是需要右上角标注引用的，这个问题我这周末增加一个命令好了，抱歉打工人时间并不是很充裕，您请见谅。
…
---- 回复的原邮件 ---- | 发件人 | @.> | | 发送日期 | 2023年11月09日 20:45 | | 收件人 | NWPUMetaphysicsOffice/Yet-Another-LaTeX-Template-for-NPU-Thesis @.> | | 抄送人 | Subscribed @.> | | 主题 | [NWPUMetaphysicsOffice/Yet-Another-LaTeX-Template-for-NPU-Thesis] 大哥好，关于引用的问题 (Issue #107) | 之前别的模版中\cite的序号是与正文一致，\upcite是在右上角，现在\cite是在右上角，请问现在如果想要与正文一致应该用什么指令，比如我在写综述的时候会用到“文献[1]研究了XXX”此时不需要放在上标 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: @.>

谢谢大佬，我去看了格式文件，在cls文件第234行“\let\oldcite\cite ”，将原来的\cite命令保存为自定义的\oldcite，就是原来的\cite的功能，有空的话可以在文献引用的说说明里提一下，谢谢大佬。
