### ISSUE TITLE
[BUG]生成的PDF转换成word后发现格式不符合指南要求

### ISSUE THREAD

**Issue by TedLau** [NWPUMetaphysicsOffice/Yet-Another-LaTeX-Template-for-NPU-Thesis#131]
**描述您的问题 (Describe the bug)**

*简洁、精准的概括您的问题（A clear and concise description of what the bug is.）例如：“在Mac OS系统下使用Tex Live 2019编译失败”*
将生成的PDF采用WPS转换成word结果发现格式不太符合写作指南要求
**环境与版本信息**
1. 代码版本(Code version)（留空则默认最新）：
2. 操作系统 (OS)：macOS 14.3.1、Windows 11均测试
3. Tex Live版本，其他Tex版本也请注明 (Version of Tex Live or other Tex distribution)：
4. Tex 编译器 (Tex compiler, eg. XeTeX): 

**错误内容 (Error contents)**

*如果您能提供错误信息（比如编译器），请在此粘贴 (Provide the error information if you could)*

**可复现内容 (Reproduceable steps)**

*请详细描述您的问题，同步贴出报错信息、日志、可复现的代码片段 (Describe your current behavior and code to reproduce the issue)*
--将生成的PDF采用WPS转换成word，发现字体大小并非小四、行间距并非20pt等
** 附加内容 (Other info, bugs and logs)**

*如果您对于此BUG有何见解或者有一些附加信息，请在此键入(Tell us your hints and thought about the bug)*
<img width="379" alt="image" src="https://github.com/user-attachments/assets/8367d0dc-d5a8-4aa7-9ddb-0b4342bdb7d6">
<img width="482" alt="image" src="https://github.com/user-attachments/assets/2fed03da-7448-4daa-9dcd-62030b96c855">

**Comment by polossk** [comment]
请直接用word书写

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年11月26日 12:13 |
| 收件人 | NWPUMetaphysicsOffice/Yet-Another-LaTeX-Template-for-NPU-Thesis ***@***.***> |
| 抄送人 | Subscribed ***@***.***> |
| 主题 | [NWPUMetaphysicsOffice/Yet-Another-LaTeX-Template-for-NPU-Thesis] [BUG]生成的PDF转换成word后发现格式不符合指南要求 (Issue #131) |

描述您的问题 (Describe the bug)

简洁、精准的概括您的问题（A clear and concise description of what the bug is.）例如：“在Mac OS系统下使用Tex Live 2019编译失败”
将生成的PDF采用WPS转换成word结果发现格式不太符合写作指南要求
环境与版本信息

代码版本(Code version)（留空则默认最新）：
操作系统 (OS)：macOS 14.3.1、Windows 11均测试
Tex Live版本，其他Tex版本也请注明 (Version of Tex Live or other Tex distribution)：
Tex 编译器 (Tex compiler, eg. XeTeX):

错误内容 (Error contents)

如果您能提供错误信息（比如编译器），请在此粘贴 (Provide the error information if you could)

可复现内容 (Reproduceable steps)

请详细描述您的问题，同步贴出报错信息、日志、可复现的代码片段 (Describe your current behavior and code to reproduce the issue)
--将生成的PDF采用WPS转换成word，发现字体大小并非小四、行间距并非20pt等
** 附加内容 (Other info, bugs and logs)**

如果您对于此BUG有何见解或者有一些附加信息，请在此键入(Tell us your hints and thought about the bug)
image.png (view on web)
image.png (view on web)

**Comment by TedLau** [comment]
好吧，谢谢
